### ISSUE TITLE
Code cannot run

### ISSUE THREAD

**Issue by haoningc** [jwlee-vcl/CTRL-C#10]
After configuring the code environment, modifying the root of the Google dataset, the training began. Results report the error. Anyone else with the same problem? Can you help me take a look?

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda3_\envs\ctrlc\lib\site-packages\torch\utils\data\_utils\worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda3_\envs\ctrlc\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3_\envs\ctrlc\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\python\CTRL-C-main\datasets\gsv_dataset.py", line 134, in __getitem__
    assert image is not None, print(img_filename)
AssertionError: None

**Comment by haaiily** [comment]
Hello, I have also encountered the same problem as you. Have you resolved it？

**Comment by haoningc** [comment]
No, I e-mailed the author. I'll get back to you if I know anything.

发自我的iPhone


------------------ Original ------------------
From: haaiily ***@***.***&gt;
Date: Mon,May 27,2024 9:17 PM
To: jwlee-vcl/CTRL-C ***@***.***&gt;
Cc: haoningc ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [jwlee-vcl/CTRL-C] Code cannot run (Issue #10)

**Comment by haaiily** [comment]
Hello, I previously inquired about the issue of your code not running. Have you resolved it recently?



***@***.***
 
From: haoningc
Date: 2024-05-27 22:20
To: jwlee-vcl/CTRL-C
CC: haaiily; Comment
Subject: Re: [jwlee-vcl/CTRL-C] Code cannot run (Issue #10)
No, I e-mailed the author. I'll get back to you if I know anything. 

发自我的iPhone 


------------------ Original ------------------ 
From: haaiily ***@***.***&gt; 
Date: Mon,May 27,2024 9:17 PM 
To: jwlee-vcl/CTRL-C ***@***.***&gt; 
Cc: haoningc ***@***.***&gt;, Author ***@***.***&gt; 
Subject: Re: [jwlee-vcl/CTRL-C] Code cannot run (Issue #10)

**Comment by haoningc** [comment]
I re-downloaded the source code package, then changed the gsv dataset path in line 250 of datasets/gsv_dataset.py. But I tested it today and thought about how it got the pitch and roll and how their errors were calculated.
