### ISSUE TITLE
Imposible to import  '_new_empty_tensor'

### ISSUE THREAD

**Issue by AdrianaGVL** [jwlee-vcl/CTRL-C#9]
```
Traceback (most recent call last):
  File "/home/agv/Calib_models/CTRL-C/main.py", line 15, in <module>
    import util.misc as utils
  File "/home/agv/Calib_models/CTRL-C/util/misc.py", line 22, in <module>
    from torchvision.ops import _new_empty_tensor
ImportError: cannot import name '_new_empty_tensor' from 'torchvision.ops' (/home/agv/anaconda3/envs/ctrlc/lib/python3.12/site-packages/torchvision/ops/__init__.py)
```
Does anyone know how to fix this issue?

Thanks in advance

**Comment by AdrianaGVL** [comment]
Solved.

In file utils/misc.py, line 21 change:
` - if float(torchvision.__version__[:3]) < 0.7:`
to
` + if float(torchvision.__version__[2:]) < 0.7:`
